### ISSUE TITLE
Read epub from bytes

### ISSUE THREAD

**Issue by masoud-c** [dteviot/epubWorkspace#5]
i have a encrypted epub file and i have to decrypt it a then show it on the EpubViewer, and it's obvious that i can't save it as file and then use it, so how can i use bytes of array to show my epub file?
 because in here:

```
   public Book(String fileName) {
    mSpine = new ArrayList<ManifestItem>();
    mManifest = new Manifest();
    mTableOfContents = new TableOfContents();
    try {
        mZip = new ZipFile(fileName);
        parseEpub();
    } catch (IOException e) {
        Log.e(Globals.TAG, "Error opening file", e);
    }
}
```

ZipFile just take an String file name

**Comment by dteviot** [comment]
I'm assuming you've got the code to decrypt the file, but are not willing to show it to me.
Which makes me suspect we're talking DRM here.  The claim you can't save as a file reinforces this suspicion.
Which makes me conclude you're doing commercial development, and expecting me to spend my free time helping you do your job.  That said, as the answer to your problem is easy, So I'll tell you how to do it.  Any further requests for help had better come with a really good reason why I should assist you.

Use http://developer.android.com/reference/java/util/zip/ZipInputStream.html.
It's constructor takes an InputStream, which you can construct from a byte array.  (Alternately, your decryption library probably has the ability to return an input stream.)
Anyway, use the ZipInputStream to decompose the zip file into the individual files (which you collect as individual arrays of bytes.)  Create a hash table that matches entry names with the individual byte arrays, and you're done.  Example of using ZipInputStream to decompose a zip file into actual files in file system: http://v4all123.blogspot.co.nz/2013/09/simple-example-for-extracting-zip-file.html
Of course, the clean way of doing this would probably be to create a new class like "EncryptedZipFile".  Give it public member functions that match the ones being used by ZipFile in this epub reader, with internals as described above, and then it's just a drop in replacement.
